# Generated by Django 4.0.6 on 2022-07-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short',
            field=models.CharField(default='nil', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
    ]
