# Generated by Django 4.0.6 on 2022-07-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_short_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
