# Generated by Django 4.0.6 on 2022-07-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_image'),
        ('home', '0007_alter_blog_date'),
    ]

    operations = [
    ]
