# Generated by Django 4.0.6 on 2022-08-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_like_created_remove_like_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
