# Generated by Django 4.0.6 on 2022-08-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='dummy-image.jpeg', upload_to=''),
        ),
    ]
